spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instruments
    username: postgres
    password: Пароль
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080

feign:
  client:
    config:
      default:
        loggerLevel: full

